server:
  port: 8772

spring:
  application:
    name: monitor-demo
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  dashboard:
    proxyStreamAllowList:
      - localhost

---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
spring:
  profiles: pro

---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  profiles: dev