server:
  port: 8771
spring:
  profiles:
    active: demo
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
spring:
  profiles: pro

---
spring:
  application:
    name: demo
  profiles: demo
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  aggregator:
    clusterConfig: DEMO
  appConfig: demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springfox.documentation.swagger.v2.path: /api-docs

---
spring:
  application:
    name: demo0
  profiles: demo0
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  aggregator:
    clusterConfig: DEMO0
  appConfig: demo0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/